# Generated by Django 6.0.5 on 2026-05-17 09:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialRisk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('clause_id', models.CharField(db_index=True, max_length=255)),
                ('financial_exposure', models.TextField()),
                ('conditions', models.TextField()),
                ('worst_case_cost', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_risks', to='documents.document')),
            ],
            options={
                'ordering': ['document', 'clause_id'],
            },
        ),
        migrations.CreateModel(
            name='RiskFinding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('clause_id', models.CharField(db_index=True, max_length=255)),
                ('risk_type', models.CharField(max_length=255)),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low'), ('safe', 'Safe')], db_index=True, max_length=20)),
                ('confidence', models.FloatField(default=0.5)),
                ('raw_explanation', models.TextField()),
                ('action', models.TextField(blank=True)),
                ('ambiguous_terms', models.JSONField(default=list)),
                ('risk_of_interpretation', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_findings', to='documents.document')),
            ],
            options={
                'ordering': ['document', 'clause_id'],
            },
        ),
    ]
